#!/bin/bash

AMI_ID=$(ec2-user@wa ~]$ aws ec2 describe-images     --region us-east-1     --image-ids ami-0c15e602d3d6c6c4a | jq '.Images[]=.ImageID')

echo -e "run instance"

aws ec2 run-instances \
 --image-id $(AIM_ID)\
 --count 1 \
 --instance-type t2.micro \