#!/bin/bash

echo "Running EC2 instance..."

# Define required variables
AMI_ID="ami-0c15e602d3d6c6c4a"
INSTANCE_TYPE="t2.micro"


# Run EC2 instance
aws ec2 run-instances \
  --image-id "$AMI_ID" \
  --count 1 \
  --instance-type "$INSTANCE_TYPE" \
